version: '3.5'
services:
  #MySQL Service
  db:
   image: mysql:latest
   container_name: db
   cap_add:
    - SYS_NICE  # CAP_SYS_NICE
   restart: unless-stopped
  tty: true
   ports:
     - "3306:3306"
   environment:
    MYSQL_DATABASE: laravel-project
     MYSQL_ROOT_PASSWORD: "Rootp@ssw0rd"
    SERVICE_TAGS: dev
     SERVICE_NAME: mysql
   volumes:
     - dbdata:/var/lib/mysql/
     - ./mysql/my.cnf:/etc/mysql/my.cnf
     - ./mysql-files:/var/lib/mysql-files
   networks:
     - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes Persistance DB
volumes:
  dbdata:
    driver: local
